esphome:
  name: es7210_integration
  platform: ESP32
  board: esp32-s3-box

external_components:
  - source:
      type: local
      path: es7210
    components: [es7210]

i2c:
  - id: bus_a
    sda: GPIO8
    scl: GPIO9
    scan: True

i2s_audio:
  - id: i2s_input
    sample_rate: 16000Hz
    bits_per_sample: 16bit
    mode: master
    dma_buf_count: 8
    dma_buf_len: 64

microphone:
  - platform: es7210
    id: es7210_mic
    i2c_id: bus_a
    i2s_audio_id: i2s_input
    sample_rate: 16000Hz
    bits_per_sample: 16bit
    i2s_din_pin: GPIO16
    adc_type: external
